---
- hosts: localhost

  tasks:
    - apt: "name={{ item }} state=present"
      with_items:
        - git
        - wget
        - curl
        - vim
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      delegate_to: aa-airbus-01
