---
- name: Install SQL Server 2019 Developer Edition
  hosts: all
  gather_facts: yes

  roles:
    - role: mssql_server
      vars:
        sql_server_media_path: "C:\\SQL2019\\Evaluation_ENU"
        sql_server_sa_password: "{{ morpheus['customOptions']['sql_pass'] }}"