---
# SQL Server version
sql_server_version: "2019"

# SQL Server edition
sql_server_edition: "Developer"

# Installation paths
sql_server_install_path: "C:\\SQLServer2019"
sql_server_config_path: "C:\\SQLServer2019\\ConfigurationFile.ini"
sql_server_media_path: "C:\\SQL2019\\Evaluation_ENU"

# Security settings
sql_server_sa_password: "{{ morpheus['customOptions']['sql_pass'] }}"  
sql_server_instance_name: "MSSQLSERVER"

# Features to install
sql_server_features: "SQLENGINE,SSMS,ADV_SSMS" 