#Compare the disks in OS with Morpheus volumes list. Skip sda and verify if other disks are partitioned and mounted as per label

---
- name: Disk count in Morpheus
  debug:
    msg: "Total number of disks on instance in Morpheus {{ disk_list_count }}./n Skipping sda check..."

- name: Iterate through morpheus volumes and check mount points
  block:
    - name: Set the initial new_disk to null
      set_fact:
        new_disk_final: null

    - name: Check each volume mount point
      block:
        - name: Check if mount point exists
          stat:
            path: "{{ item.name }}"
          register: mount_point_stat
          when: item.deviceName != '/dev/sda'
          loop: "{{ morpheus['instance']['containers'][0]['server']['volumes'] }}"

        - name: Set the new_disk fact if mount point does not exist
          set_fact:
            new_disk_final: "{{ item.deviceName | regex_replace('/dev/', '') }}"
          when: not mount_point_stat.stat.exists and item.deviceName != '/dev/sda'
          loop: "{{ morpheus['instance']['containers'][0]['server']['volumes'] }}"
          loop_control:
            label: "{{ item.name }}"
          register: new_disk_fact

    - name: Debug new_disk_fact
      debug:
        var: new_disk_fact

    - name: Debug final new_disk
      debug:
        var: new_disk_final

    - name: Include additional tasks if new_disk_final is defined
      include_tasks: new_disk.yml
      vars:
        new_disk: "{{ new_disk_final }}"
      when: new_disk_final is not none
  when: disk_list_count_int == disk_data_count_int