---
- name: Check if SQL Server is already installed
  win_shell: |
    $installed = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*SQL Server*" }
    if ($installed) {
      Write-Output "SQL Server is already installed"
      exit 1
    } else {
      Write-Output "SQL Server is not installed"
      exit 0
    }
  register: sql_check
  ignore_errors: true

- name: Create SQL Server installation directory
  win_file:
    path: "{{ sql_server_install_path }}"
    state: directory
  when: sql_check.rc == 0

- name: Create SQL Server configuration file
  win_template:
    src: ConfigurationFile.ini.j2
    dest: "{{ sql_server_config_path }}"
  when: sql_check.rc == 0

- name: Install SQL Server 2019
  win_shell: |
    $setup = "{{ sql_server_media_path }}\setup.exe"
    $config = "{{ sql_server_config_path }}"
    & $setup /ConfigurationFile=$config
  register: sql_install_result
  when: sql_check.rc == 0

- name: Check SQL Server service status
  win_service:
    name: "MSSQLSERVER"
    state: started
    start_mode: auto
  register: sql_service_status

- name: Check SQL Browser service status
  win_service:
    name: SQLBrowser
    state: started
    start_mode: auto
  register: browser_service_status

- name: Check if SQL Server port is open
  win_shell: |
    $rule = Get-NetFirewallRule -Name "SQLServer" -ErrorAction SilentlyContinue
    if ($rule) {
      Write-Output "SQL Server port rule exists"
      exit 1
    } else {
      Write-Output "SQL Server port rule does not exist"
      exit 0
    }
  register: sql_port_check
  ignore_errors: true

- name: Check if SQL Browser port is open
  win_shell: |
    $rule = Get-NetFirewallRule -Name "SQLBrowser" -ErrorAction SilentlyContinue
    if ($rule) {
      Write-Output "SQL Browser port rule exists"
      exit 1
    } else {
      Write-Output "SQL Browser port rule does not exist"
      exit 0
    }
  register: browser_port_check
  ignore_errors: true

- name: Open SQL Server port in Windows Firewall
  win_firewall_rule:
    name: SQLServer
    localport: 1433
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
  when: (sql_service_status.changed or sql_install_result.changed) and sql_port_check.rc == 0

- name: Open SQL Server Browser port in Windows Firewall
  win_firewall_rule:
    name: SQLBrowser
    localport: 1434
    action: allow
    direction: in
    protocol: udp
    state: present
    enabled: yes
  when: (browser_service_status.changed or sql_install_result.changed) and browser_port_check.rc == 0 